export interface Step {
    id: string;
    title: string;
    content: string;
    greek?: string;
    media: 'image' | 'video' | 'schematic' | 'none';
    mediaUrl?: string; // e.g. "reference/glottis_illustration(1).png"
    reference?: string;
    timeRange?: [number, number];
}

import glossaryData from './glossary.json';

export interface GlossaryEntry {
    greek: string;
    term: string;
    def: string;
    url?: string;
}

// Single source of truth: edit glossary.json, not this file.
// The pre-commit hook automatically syncs it to index.html.
export const GLOSSARY = glossaryData as unknown as Record<string, GlossaryEntry>;

export const SCRIPT_PNEUMA: Step[] = [
    {
        id: "pneuma_intro",
        title: "I. Pneuma and Voice",
        content: "Galen recognises three kinds of <Pneuma>pneuma</Pneuma>: natural (φυσικόν) elaborated in the liver, vital (ζωτικόν) in the heart and arteries, and psychic (ψυχικόν) in the brain and nerves. Two of these play distinct roles in phonation: psychic pneuma governs voluntary motor control of the larynx, while the thoracic pneuma, once forcibly expelled as <Ekphysesis>ἐκφύσησις</Ekphysesis>, furnishes the material substance of voice.",
        media: "schematic",
        reference: "Singer 2020, 'The Concept of Pneuma after Aristotle,' pp. 251–270; PHP 7.3.27–28"
    },
    {
        id: "pneuma_brain",
        title: "1. Voluntary Control: Psychic Pneuma",
        content: "The capacity for voluntary phonation originates in the brain (ἐγκέφαλος), which transmits psychic pneuma through the <Nerves>recurrent laryngeal nerves</Nerves> (τό παλινδρομοῦν νεῦρον) to the intrinsic muscles of the larynx. Galen stresses that severing these nerves destroys voice instantly, even while ordinary breathing continues — the nerve, not the brain, is the proximate cause of laryngeal action. The brain's role sets the voluntary intent; the recurrent nerve executes it.",
        media: "schematic",
        reference: "AA 11 (Arabic, trans. Duckworth); UP 7.8–9"
    },
    {
        id: "pneuma_thorax",
        title: "2. Material of Voice: Ekphysēsis",
        content: "Voice requires not ordinary exhalation (ἐκπνοή) but <Ekphysesis>ἐκφύσησις</Ekphysesis> — 'a kind of sudden and vehement ἐκπνοή' (AA 8.7). The distinction is crucial: patients who suffer damage to De Loc. Aff. 3.9 retain the ability to breathe while losing the capacity to produce voice, because ἐκφύσησις is a separate muscular activity (ἐνέργεια), generated by the thoracic and abdominal muscles with degrees of force (ῥώμη). It is 'a kind of suitable material of voice' (ὕλη τις οἰκεία φωνῆς) — not voice itself, but the substance from which voice will be made.",
        media: "schematic",
        reference: "AA 8.7; De Loc. Aff. 3.9; De Voce 1.1 (Latin)"
    },
    {
        id: "pneuma_trachea",
        title: "3. Preprocessing: The Trachea",
        content: "Before reaching the larynx the <Ekphysesis>ἐκφύσησις</Ekphysesis> travels up the trachea (ἀρτηρία τραχεῖα), whose cartilaginous rings stabilise and direct the ascending column of air. Galen notes that the trachea 'preprocesses' (προρρυθμίζει) the breath so that it arrives at the <Glottis>glōttis</Glottis> already organised — not yet at the velocity required for voice, but conditioned for the acceleration the glōttis will provide. At this stage the ἐκφύσησις is still pre-vocal matter in transit.",
        media: "schematic",
        reference: "UP 7.4; UP 7.13"
    },
    {
        id: "pneuma_larynx",
        title: "4. Acceleration: The Glottis Narrows",
        content: "The <Glottis>glōttis</Glottis> narrows the passage from wide to narrow and back to wide — a graduated constriction, not a simple valve. This narrowing accelerates the <Ekphysesis>ἐκφύσησις</Ekphysesis>, converting volume into speed (ῥώμη). Excess air deflected sideways into the laryngeal ventricles undergoes what Galen calls a <Whirlpool>ἴλιγγος</Whirlpool> ('whirlpool experience'): it spins within the cavities without pressing against the closed lips, allowing the glōttis to remain narrowed. Narrowing, ventricle storage, and acceleration act together as an integrated mechanism.",
        media: "schematic",
        reference: "UP 7.13"
    },
    {
        id: "pneuma_strike",
        title: "5. The Strike (Πληγή)",
        content: "The <Muscles>thyroarytenoid muscles</Muscles>, innervated by the <Nerves>recurrent laryngeal nerves</Nerves>, hold the arytenoid cartilage firm against the ascending ἐκφύσησις. The accelerated stream is then struck by the laryngeal cartilages 'as if struck by some plectrums' — the impact (<Plēgē>πληγή</Plēgē>) is the generative act. Galen insists on συμμετρία (proportionality): the mass of the cartilage and the force of the ἐκφύσησις must be matched so that the air resists briefly before yielding. Too weak a stream passes unimpeded; too strong a one disperses. Only the proportionate strike produces voice.",
        media: "schematic",
        reference: "PHP 2.4.26–28; UP 7.4"
    },
    {
        id: "pneuma_voice",
        title: "6. Emergence of Voice (Φωνή)",
        content: "\"What rises beforehand is not yet <Voice>voice</Voice>, but a kind of matter suitable for voice, which we call <Ekphysesis>ἐκφύσησις</Ekphysesis>\" (PHP 2.5.53). Voice (φωνή) is defined as 'meaningful sound' (σημαντικὸς ψόφος) and is not the air itself but what the air becomes once struck: a structured, resonant event that 'reports the thoughts of the mind.' The process is therefore a transformation — from ordinary breath, to ἐκφύσησις, to the proportionate strike, to φωνή — each stage necessary, none sufficient alone.",
        media: "schematic",
        reference: "PHP 2.5.53"
    }
];

export const SCRIPT_LARYNX: Step[] = [
    {
        id: "intro_instrument",
        title: "The Larynx: Instrument of voice",
        content: "\"Voice is the foremost vehicle of thought: a vivid and living bridge between the soul and the world beyond.\" Galen defines it as a mechanism involving specific anatomical structures.",
        media: "image",
        mediaUrl: "reference/glottis_illustration(1).png"
    },
    {
        id: "cartilages",
        title: "1. Cartilages of the Larynx",
        content: "The <Thyroid>Thyroid</Thyroid> is \"a large, shield-shaped cartilage in the front of the larynx.\" The <Cricoid>Cricoid</Cricoid> is \"said to have a circular shape, like a ring.\" The <Arytenoid>Arytenoid</Arytenoid> is mentioned \"as one rather than two separate structures... the term derives from ἀρύταινα, denoting 'jug.'\"",
        media: "image",
        mediaUrl: "reference/glottis_illustration(1).png"
    },
    {
        id: "muscles",
        title: "2. Laryngeal Muscles",
        content: "Galen identifies twelve <Muscles>Special Muscles</Muscles>. \"Among this group... the thyroarytenoid muscles are the most crucial for phonation... responsible for closing [the glottis]... Galen remarks that nature (φύσις) has demonstrated superb skill in constructing them.\"",
        media: "image",
        mediaUrl: "reference/glottis_illustration(1).png"
    },
    {
        id: "nerves",
        title: "3. Laryngeal Nerves",
        content: "\"The <Nerves>recurrent laryngeal nerves</Nerves> (τό παλινδρομοῦν νεῦρον) are described as two small nerves ascending from below... Galen names it 'unjust' (ἄδικον) that this nerve would not reach from the brain, and he praises nature for constructing it the way it is.\"",
        media: "image",
        mediaUrl: "reference/glottis_illustration(1).png"
    },
    {
        id: "glottis_def",
        title: "4. The Glottis (τι σῶμα)",
        content: "\"In its inner cavity... is fixed <Glottis>a certain body</Glottis>... that resembles neither in substance nor in structure to any of the other body parts... which indeed I name glōttis and the tongue of the larynx.\"",
        media: "image",
        mediaUrl: "reference/glottis_illustration(1).png"
    },
    {
        id: "ekphysesis",
        title: "5. The Material: Ekphysesis",
        content: "\"Phonation requires <Ekphysesis>Ekphysesis</Ekphysesis>... a forceful, muscularly generated exhalation with degrees of intensity, and as an activity (ἐνέργεια)... 'a kind of suitable material of voice' (ὕλη τις οἰκεία φωνῆς).\"",
        media: "video",
        mediaUrl: "reference/glottis animation.mp4",
        timeRange: [0, 5]
    },
    {
        id: "narrowing",
        title: "6. The Narrowing",
        content: "The structure of the valves \"makes the air spin inside in what Galen calls 'some kind of a <Whirlpool>whirlpool experience</Whirlpool>' (οἷον ἴλιγγόν τινα παθὸν).\"",
        media: "video",
        mediaUrl: "reference/glottis animation.mp4",
        timeRange: [5, 10]
    },
    {
        id: "strike",
        title: "7. The Strike (Plēgē)",
        content: "\"For the <Ekphysesis>Ekphysesis</Ekphysesis>, which is <Strike>struck</Strike> by the cartilages of the larynx as if it were struck by some plectrums, becomes this voice.\"",
        media: "video",
        mediaUrl: "reference/glottis animation.mp4",
        timeRange: [10, 15]
    }
];

export const SCRIPT_ANALYSIS: Step[] = [
    {
        id: "analysis_intro",
        title: "1. The Nature of the Glottis",
        content: "The muscles and the cartilages of the larynx were indeed described: it shall be spoken now about the other parts in what follows. In its (the larynx's) inner cavity, through which pneuma passes in and out, is fixed a certain body, on which I shortly spoke before, that resembles neither in substance nor in structure to any of the other body parts in all of the body. I have also spoken about it in my treatise On The Voice, showing that it is the first and the most proper organ of the voice, and it will be said now, as much as is necessary for the present affairs.",
        greek: "Περὶ μὲν δὴ τῶν μυῶν τε καὶ τῶν χόνδρων τοῦ λάρυγγος εἴρηται· περὶ δὲ τῶν ἄλλων ἐφεξῆς λεγέσθω. κατὰ τὴν ἔνδον χώραν αὐτοῦ, δι' ἧς εἴσω τε καὶ ἔξω τὸ πνεῦμα φέρεται, τέτακταί τι σῶμα, περὶ οὗ μικρὸν ἔμπροσθεν εἶπον, οὔτε τὴν οὐσίαν, οὔτε τὸ σχῆμα παραπλήσιον ἑτέρῳ τινὶ τῶν καθ' ὅλον τὸ ζῶον. ὑπὲρ οὗ λέλεκται μέν μοι κᾀν τοῖς περὶ φωνῆς, ἐπιδεικνύντι τὸ πρῶτόν τε καὶ κυριώτατον ὑπάρχειν αὐτὸ τῆς φωνῆς ὄργανον· εἰρήσεται δὲ καὶ νῦν, ὅσον εἰς τὰ παρόντα ἐστὶ χρήσιμον",
        media: "image",
        mediaUrl: "reference/glottis_illustration(1).png",
        reference: "Gal. UP.7.13, 407,19 - 26 Helmreich = 3.560 - 561 Kühn"
    },
    {
        id: "analysis_aulos",
        title: "2. The Aulos Analogy",
        content: "It resembles the mouthpiece (glōttis) of an aulos (ἀυλός), especially when it is viewed from below or above. I mean below, where the (rough) artery and the larynx meet [Cricotracheal ligament]: I mean above, through the orifice that is formed by the borders of the arytenoid and thyroid cartilages. It would be better not to liken that body to the mouthpieces of auloi, but rather to liken the mouthpieces to that body.",
        greek: "ἔοικε μὲν οὖν αὐλοῦ γλώττῃ, μάλιστα κάτωθέν τε καὶ ἄνωθεν αὐτὸ θεωμένῳ. λέγω δὲ κάτωθεν μὲν, ἵνα συνάπτουσιν ἀλλήλοις ἥ τ' ἀρτηρία καὶ ὁ λάρυγξ· ἄνωθεν δὲ, κατὰ τὸ στόμα τὸ γεννώμενον ὑπὸ τῶν ταύτῃ περάτων τοῦ τε ἀρυταινοειδοῦς χόνδρου καὶ τοῦ θυρεοειδοῦς. ἄμεινον δ' ἦν ἄρα μὴ τοῦτο τὸ σῶμα ταῖς τῶν αὐλῶν γλώτταις εἰκάζειν, ἀλλ' ἐκείνας τῷδε.",
        media: "image",
        mediaUrl: "reference/glottis_illustration(1).png",
        reference: "Gal. UP. 7. 13. 407-8. 26-18 Helmreich = 3. 561 Kühn"
    },
    {
        id: "analysis_nature_craft",
        title: "3. Nature vs. Craft",
        content: "For I think nature is prior in time and wiser in actions than the 'craft'. Therefore, this body (glōttis) is a deed of nature, and that which in the aulos is an invention of skill, that (the invention) would be an imitation of it (the body), invented by a wise man who is able to understand and imitate the deeds of nature. Well, the aulos is useless without its mouthpiece; the evidence proves that. There is no need to yearn to hear the reason in this work, for it was said in the treatise On the Voice, where it was straightforwardly demonstrated that it is not possible to generate a voice without the narrowing of the passage.",
        greek: "καὶ γὰρ καὶ πρότερον, οἶμαι, τῷ χρόνῳ καὶ σοφώτερον τοῖς ἔργοις ἡ φύσις τῆς τέχνης ἐστίν. ὥστ', εἴπερ τουτὶ μὲν τὸ σῶμα φύσεως ἔργον ὑπάρχει, τέχνης δ'εὕρημά ἐστι τὸ κατὰ τοὺς αὐλοὺς, ἐκεῖνο τούτου μίμημα ἂν εἴη, πρὸς ἀνδρὸς εὑρημένον σοφοῦ, γνωρίζειν τε καὶ μιμεῖσθαι τὰ τῆς φύσεως ἔργα δυναμένου. ὅτι μὲν οὖν χωρὶς τῆς γλώττης ἄχρηστος ὁ αὐλὸς, αὐτὸ δείκνυσι τὸ φαινόμενον. αἰτίαν δ' οὐ χρὴ ποθεῖν ἀκούειν ἐν τῷ παρόντι λόγῳ. λέλεκται γὰρ ἐν τῇ περὶ φωνῆς πραγματείᾳ, καθ' ἣν καὶ τοῦτο εὐθὺς ἀποδέδεικται, τὸ μὴ δύνασθαι γενέσθαι φωνὴν ἄνευ τοῦ στενωθῆναι τὴν διέξοδον.",
        media: "image",
        mediaUrl: "reference/glottis_illustration(1).png",
        reference: "Gal. UP. 7. 13. 408. 7-18 Helmreich = 561 Kühn"
    },
    {
        id: "analysis_narrowing",
        title: "4. Necessity of Narrowing",
        content: "For if only the whole passage would entirely fall back, while the first two cartilages (thyroid and cricoid) are loosed and separated from each other, and the third (arytenoid) lied open, lest ever it would be possible to produce voice: but if the pneuma would be carried with no motion outside, a soundless expiration will be achieved: but if the pneuma would be carried at once and vehemently, what is called \"to sigh\" will be produced. In order that the animal would phonate, it requires a sudden carrying (of pneuma) from all of the parts below, and it requires no less of that and the passage in the larynx to be narrow and not simply narrow, but it is led gradually from the wide to the narrow part, and gradually it is widens again back from the narrow part. That is exactly how that body in our current discussion works, which indeed I name glōttis and the tongue of the larynx.",
        greek: "εἰ γὰρ ἀναπεπταμένη τελέως εἴη σύμπασα, κεχαλασμένων μὲν τῶν πρώτων δυοῖν χόνδρων καὶ διεστώτων ἀπ' ἀλλήλων, ἀνεῳγμένου δὲ τοῦ τρίτου, μή ποτ' ἂν δύνασθαι γενέσθαι φωνήν· ἀλλ' εἰ μὲν ἀτρέμα τὸ πνεῦμα ἔξω φέροιτο, τὴν χωρὶς ψόφου συντελουμένην ἐκπνοήν· εἰ δ' ἀθρόως τε καὶ σφοδρῶς, τὸ καλούμενον στενάζειν γιγνόμενον. ἵνα δὲ φωνήσῃ τὸ ζῶον, δεῖσθαι πάντως καὶ τῆς κάτωθεν φορᾶς ἀθροωτέρας, δεῖσθαι δ' οὐδὲν ἧττον ταύτης καὶ τῆς κατὰ τὸν λάρυγγα διεξόδου στενωτέρας, καὶ οὐχ ἁπλῶς γε στενωτέρας, ἀλλὰ κατὰ βραχὺ μὲν ἐξ εὐρέος εἰς στενὸν ἀγομένης, κατὰ βραχὺ δ' ἐκ τοῦ στενοῦ πάλιν εὐρυνομένης. ὅπερ ἀκριβῶς ἐργάζεται τουτὶ τὸ σῶμα τὸ προκείμενον ἐν τῷ λόγῳ νῦν, ὃ δὴ γλωττίδα τε καὶ γλῶσσαν ὀνομάζω λάρυγγος.",
        media: "video",
        mediaUrl: "reference/glottis animation.mp4",
        reference: "Gal. UP. 7. 13. 408-409. 18-7 Helmreich = 3. 561-562 Kühn"
    },
    {
        id: "analysis_muscles",
        title: "5. Muscles and Glottis",
        content: "For the muscles confining the arytenoid cartilage forcibly holding out against the pushed pneuma, to that function the nature of the aforesaid glōttis significantly contributes. For the parts of the glōttis, both the left and the right [the vocal folds and vestibular folds], come to it, so that they fall together to each other and accurately shut the passage [rima glottidis].",
        greek: "ἀντέχουσι γὰρ οὗτοι βιαίως ὠθουμένῳ τῷ πνεύματι τὸν ἀρυταινοειδῆ κλείοντες χόνδρον. εἰς ὅπερ ἔργον οὐ σμικρὰ συντελεῖ τῆς προειρημένης γλωττίδος ἡ φύσις. εἰς ταὐτὸν γὰρ αὐτῆς ἔρχεται τὰ μόρια, τό τ' ἐκ τῶν ἀριστερῶν καὶ τὸ τῶν δεξιῶν, ὡς συμπεσεῖν ἀλλήλοις ἀκριβῶς καὶ κλείεσθαι τὸν πόρον.",
        media: "video",
        mediaUrl: "reference/glottis animation.mp4",
        reference: "Gal. UP. 7. 13. 409. 15-21 Helmreich = 3. 563 Kühn"
    },
    {
        id: "analysis_cavities",
        title: "6. Apertures and Cavities",
        content: "And if some small unshut (passage) would be left, and especially in the animals where the whole larynx is wider, as such case was shown in the larger-voiced animals, that unguarded aperture is not disregarded by nature, placing under each part of the glōttis a considerable inner cavity in the aperture. whenever the air makes use of the broad ways as it enters and exits the body back and forth, none of it is pushed aside into the cavity: but since the passage is blocked and confined the air is thrusted vehemently toward the flanks and opens the small mouth of the glōttis, which until then was closed by the folding of the lips. For that very thing, that is of the folding, is the reason that aperture, discussed in this treatise, escaped the notice of all of the previous anatomists. Having the cavities in the tongue of the larynx filled with pneuma, air is poured off presumably in the necessary mass to that passage of the pneuma, and narrow it exactly, as if they opened it by little before. That skill of nature came into high accuracy regarding the tongue of the larynx in all its structure and in size and arrangement and in the apertures and cavities.",
        greek: "εἰ δ' ἔτι σμικρὸν ἄκλειστον ὑπολειφθείη, καὶ μάλιστα ἐν οἷς ζώοις εὐρύτερός ἐστιν ὁ σύμπας λάρυγξ, (ἐδείχθη δὲ τοιοῦτος ἐν τοῖς μεγαλοφώνοις ὑπάρχων,) οὐδὲ τοῦτο ἀπρονόητον παρῶπται τῇ φύσει, τρῆμα καθ' ἑκάτερον μέρος τῆς γλωττίδος ἓν ἐργασαμένη, ὑποθείσῃ δὲ τῷ τρήματι κοιλίαν ἔνδον οὐ σμικράν. εἰς ἣν, ἐπειδὰν μὲν εὐρείαις ὁδοῖς ὁ ἀὴρ χρώμενος εἰσίῃ τε εἰς τὸ ζῶον καὶ ἐξίῃ αὖθις, οὐδὲν παρωθεῖται· φραχθείσης δὲ τῆς διεξόδου, στενοχωρούμενος ὠθεῖταί τε βιαίως πρὸς τὰ πλάγια καὶ τὸ τῆς γλωττίδος ἀνοίγνυσι στόμιον, ὃ τέως ἐκέκλειστο, τῶν χειλῶν ἐπεπτυγμένων. αὐτὸ γάρ τοι τοῦτο (τοῦτ' ἔστι τὸ τῆς ἐπιπτύξεως) αἴτιον τοῦ λαθεῖν ἅπαντας τοὺς ἔμπροσθεν ἀνατομικοὺς τὸ προκείμενον ἐν τῷ λόγῳ τρῆμα. πληρωθεισῶν δὲ πνεύματος τῶν ἐν τῇ γλώττῃ τοῦ λάρυγγος κοιλιῶν, ἀποχεῖσθαι μὲν δήπου τὸν ὄγκον ἀναγκαῖον εἰς αὐτὸν τοῦ πνεύματος τὸν πόρον, ἀκριβῶς δὲ στενοῦσθαι, κᾂν εἰς μικρόν τι πρόσθεν ἀνέῳκτο. αὕτη μὲν ἡ περὶ τὴν γλῶτταν τοῦ λάρυγγος τέχνη τῆς φύσεως ἔν τε τῷ σύμπαντι σχήματι καὶ τῷ μεγέθει καὶ τῇ θέσει καὶ τοῖς τρήμασι καὶ ταῖς κοιλίαις εἰς ἄκρον ἀκριβείας ἥκουσα.",
        media: "video",
        mediaUrl: "reference/glottis animation.mp4",
        reference: "Gal. UP. 7. 13. 409-410. 21-16 Helmreich = 3. 563-564 Kühn"
    },
    {
        id: "analysis_utility",
        title: "7. Utility and Size",
        content: "Well if you will have in mind it (the tongue of the larynx) having been made bigger, you will block the ways of the pneuma, as it is accustomed to block them in inflammations. And having been made smaller, it will be more deficient of the right size and the animal act entirely mute: having lost only a little of such part the animal act as small-voiced and bad-voiced, in such way that it [the tongue of the larynx] lacks its proper size. And so shall you alter its position, or the size of the aperture or the cavity, you will destroy the whole utility.",
        greek: "μείζονα γοῦν αὐτὴν εἴπερ ἐπινοήσαις γεγενημένην, ἀποφράξεις τὰς ὁδοὺς τοῦ πνεύματος, ὡς κἀν ταῖς φλεγμοναῖς ἀποφράττειν εἴωθεν. ἐλάττων δ' αὖ γενηθεῖσα, πολὺ μὲν ἐνδέουσα τοῦ μετρίου παντάπασιν ἄφωνον ἐργάζεται τὸ ζῷον· ὀλίγῳ δ' ἀπολειφθεῖσα μέρει τοσούτῳ μικροφωνότερόν τε καὶ κακοφωνότερον, ὅσῳπερ ἂν αὐτὴ λείπηται τοῦ συμμέτρου. οὕτω δὲ κἂν τὴν θέσιν αὐτῆς μετακινή- σῃς, ἢ τὸ μέγεθος τοῦ τρήματος ἢ τῆς κοιλίας ἀναιρήσεις ‖ τὴν ὅλην χρείαν.",
        media: "video",
        mediaUrl: "reference/glottis animation.mp4",
        reference: "Gal. UP. 7. 13. 410. 16-25 Helmreich = 3. 564-565 Kühn"
    },
    {
        id: "analysis_whirlpool",
        title: "8. The Whirlpool (Iliggos)",
        content: "Indeed, immediately along each aperture, as said, there is a part that is elongated from above downwards, as some narrow line, and yet it is not really narrow: but the membranous substance of the lips is as it is falling into the underlying concavity, and through that it seems more as a wrinkle rather than aperture before the lips unfold. And when they unfold it (the wrinkle) is immediately clearly observed, and clearly the underlying cavity to it. And being each of the apertures from the left and the right as such, some pneuma flows beside them with no reason to open the little-mouth or the filled cavity. Whenever it is pushed vehemently from below, and restrained from above, inasmuch as no more force to go straightforward, as some whirlpool experience, spinning toward the flanks of the passage, falling into them vehemently and arousing easily the membranous growths of each of the passages to the underlying concavities, to those which they incline by nature, filling and blowing through the entire glōttis.",
        greek: "αὐτίκα γέ τοι τὸ τρῆμα καθ' ἑκάτερον, ὡς εἴρηται, μέρος ὑπάρχει, πρόμηκες δ' ἐστὶν ἄνωθεν κάτω, καθάπερ τις γραμμὴ στενή, καίτοι γ' οὐκ ὂν στενόν, ἀλλὰ τὸ τῶν χειλῶν ὑμενῶδες οἷόνπερ καταπῖπτον ἐστὶν εἰς τὴν ὑποκειμένην κοιλότητα, καὶ διὰ τοῦτο καθάπερ ῥυσότης μᾶλλον ἢ τρῆμα φαίνεται πρὶν διαπτυχθῆναι τὰ χείλη. διαπτυχθέντων δὲ σαφῶς μὲν ἤδη καὶ τοῦτο, σαφῶς δὲ καὶ ἡ ὑποκειμένη κοιλότης αὐτῷ θεωρεῖται. τοιούτου δ' ὄντος ἑκατέρου τοῦ τρήματος ἐξ ἀριστερῶν τε καὶ δεξιῶν παραρρεῖ τι πνεῦμα μηδεμίαν αἰτίαν ἔχον δεξιῶν παραρρεῖ τι πνεῦμα μηδεμίαν αἰτίαν ἔχον ἀνοιγνύναι τὸ στόμιον ἢ πληροῦν τὴν κοιλίαν. ὅταν δ' ὠθῆται μὲν κάτωθεν βιαίως, ἴσχηται δ' ἄνωθεν, ἅτε μηκέτι δυνάμενον εὐθυπορεῖν, οἷον ἴλιγγόν τινα παθὸν ἐπιστρέφεταί τε πρὸς τὰ πλάγια τοῦ πόρου καὶ τούτοις ἐμπίπτει βιαίως ἀνατρέπει τε ῥᾳδίως τὰς ὑμενώδεις ἐπιφύσεις ἑκατέρου τῶν πόρων εἰς τὰς ὑποκειμένας κοιλότητας, εἰς ἅσπερ καὶ ῥέπουσι φύσει, πληροῖ τ' αὖ καὶ διαφυσᾷ ‖ σύμπασαν τὴν γλωττίδα.",
        media: "video",
        mediaUrl: "reference/glottis animation.mp4",
        reference: "Gal. UP. 7. 13. 410-411. 25-17 Helmreich = 3. 565-566 Kühn"
    },
    {
        id: "analysis_protection",
        title: "9. Protection Against Breaking",
        content: "Since that, it is followed by necessity that the passage is blocked precisely. And that body of the glōttis was made of a membranous material not to break from being filled with pneuma and not at the time when the whole larynx widens and not when it contracts, obeying the opposing conditions of it (of the larynx), ever reaching the danger of breaking.",
        greek: "τούτῳ δ' ἐξ ἀνάγκης ἕπεται φράττεσθαι τὸν πόρον ἀκριβῶς. αὐτὸ δὲ τὸ σῶμα τῆς γλωττίδος ὑμενῶδες μὲν ἐγένετο πρὸς τὸ μήτε πληρούμενον ὑπὸ τοῦ πνεύματος ῥήγνσθαι μήτ' ἐν τῷ ποτὲ μὲν εὐρύνεσθαι, ποτὲ δὲ συστέλλεσθαι τὸν ὅλον λάρυγγα, ταῖς ἐναντίαις αὐτοῦ καταστάσεσιν ἑπόμενον, εἰς κίνδυνον ἀφικέσθαι ποτὲ ῥήξεως·",
        media: "video",
        mediaUrl: "reference/glottis animation.mp4",
        reference: "Gal. UP. 7. 13. 411. 17-24 Helmreich = 3. 566 Kühn"
    },
    {
        id: "analysis_moisture",
        title: "10. The Necessity of Moisture",
        content: "and it is not simply moist, but with sticky and fatty liquid, in order to moisten by all fitting moist and not, as in the tongues of the auloi, that dry up continuously, requiring some additional liquid, and that becomes in need of external remedies. For the delicate and watery liquid being quickly dismissed into vapours, disperse and flow off easily straightway and much whenever the passage is inclined: and the sticky and fatty liquid suffices for much time and it does not readily flow off and not dry out. Therefore, if nature devised all other things in the structure of the larynx admirably, neglecting only the liquid of such sort, our voice would be corrupted because of quick dryness of the glōttis as well as all of the laryngeal structures, as now it is used to be rarely when the administration of nature is conquered by violent circumstances. For in burning fevers people cannot utter without wetting the larynx, and similarly in those that walked through the violent heat.",
        greek: "ὑγρὸν δ' οὐχ ἁπλῶς, ἀλλὰ σὺν τῷ γλίσχρον τέ πως εἶναι καὶ λιπαρόν, ἵν' ἐπιτέγγηται διὰ παντὸς οἰκείᾳ νοτίδι καὶ μή, καθάπερ αἱ τῶν αὐλῶν γλῶτται ξηραινόμεναι συνεχῶς ἐπικτήτου τινὸς ὑγρότητος δέονται, καὶ αὐτὸ τῶν ἔξωθεν ἰαμάτων ἐπιδεὲς γίγνηται. τὸ μὲν γὰρ λεπτὸν καὶ ὑδατῶδες ὑγρὸν εἰς ἀτμοὺς τὸ μὲν γὰρ λεπτὸν καὶ ὑδατῶδες ὑγρὸν εἰς ἀτμοὺς διαλυόμενον ἐν τάχει διαφορεῖται ῥᾳδίως ἀπορρεῖ τε παραχρῆμα καὶ μάλισθ' ὅταν ᾖ κατάντης ὁ πόρος· τὸ δὲ γλίσχρον ἅμα καὶ λιπαρὸν ἐξαρκεῖ χρόνῳ παμπόλλῳ μήτ' ἀπορρέον ἑτοίμως μήτε ξηραινόμενον. ὥστ', εἴπερ καὶ τἄλλα πάνθ' ἡ φύσις ἐν τῇ τοῦ λάρυγγος κατα- σκευῇ θαυμαστῶς ἐτεχνήσατο, μόνης δὲ τῆς τοιαύτης ὑγρότητος ἐπελάθετο, διεφθείρετ' ἂν ‖ ἡμῶν ἡ φωνὴ διὰ ταχέων ξηραινομένης τῆς γλωττίδος ἅμα τοῖς κατὰ τὸν λάρυγγα σύμπασιν, ὥσπερ νῦν εἴωθε γίγνεσθαι σπανιάκις ὑπὸ βιαίων αἰτίων νικωμένης τῆς φυσικῆς διοικήσεως. ἔν τε γὰρ τοῖς περικαέσι πυρετοῖς οὐ δύνανται φθέγγεσθαι πρὶν διαβρέξαι τὸν λάρυγγα, καὶ ὅσοι διὰ καύματος ὡδοιπόρησαν σφοδροῦ.",
        media: "video",
        mediaUrl: "reference/glottis animation.mp4",
        reference: "Gal. UP. 7. 13. 411-412. 25-14 Helmreich = 3. 566 Kühn"
    }
];
